app = "aptlast"
primary_region = "hkg"

[env]
DB_URL = "jdbc:mysql://my-mysql-db-billowing-frog-9310.internal:3306/aptcommunitydb"
DB_USERNAME = "root"
DB_PASSWORD = "1234"

[build]
builder = "paketobuildpacks/builder:base"

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
