app = "aptlast"
primary_region = "hkg"

[env]
DB_URL = "jdbc:mysql://my-mysql-db-billowing-frog-9310.internal:3306/aptcommunitydb"
DB_USERNAME = "root"
DB_PASSWORD = "1234"
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
