spring.application.name=AptCommunitySB

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ?????? ?? ?? (Railway ??)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ??? ? (?? HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.web.resources.cache.cachecontrol.no-cache=true
spring.devtools.restart.enabled=true

server.servlet.context-path=/AptCommunity

logging.level.root=INFO

logging.level.org.springframework=WARN

logging.level.com.springmvc=DEBUG
