spring.application.name=AptCommunitySB

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://localhost:3306/aptcommunitydb
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.no-cache=true
spring.devtools.restart.enabled=true

server.servlet.context-path=/AptCommunity
